
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.10.0
 * Query Engine version: 0edf323efd1d98336f3f0a68684b56f689b900d3
 */
Prisma.prismaVersion = {
  client: "7.10.0",
  engine: "0edf323efd1d98336f3f0a68684b56f689b900d3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  websiteUrl: 'websiteUrl',
  linkedinUrl: 'linkedinUrl',
  industry: 'industry',
  fundingStage: 'fundingStage',
  companySizeRange: 'companySizeRange',
  employeeCount: 'employeeCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCoverLetterScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  customLabel: 'customLabel',
  recipientName: 'recipientName',
  recipientTitle: 'recipientTitle',
  recipientCompany: 'recipientCompany',
  recipientAddress: 'recipientAddress',
  recipientRole: 'recipientRole',
  date: 'date',
  salutation: 'salutation',
  experienceParagraph1: 'experienceParagraph1',
  experienceParagraph2: 'experienceParagraph2',
  companyMotivation: 'companyMotivation',
  callToAction: 'callToAction',
  signoff: 'signoff',
  explanation: 'explanation',
  storageKey: 'storageKey',
  pdfStatus: 'pdfStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCoverLetterOutboxScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  status: 'status',
  forceRegenerate: 'forceRegenerate',
  attempts: 'attempts',
  lastError: 'lastError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCurriculumScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  storageKey: 'storageKey',
  pdfStatus: 'pdfStatus',
  explanation: 'explanation',
  customLabel: 'customLabel',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCurriculumWorkScalarFieldEnum = {
  id: 'id',
  curriculumId: 'curriculumId',
  name: 'name',
  position: 'position',
  summary: 'summary',
  include: 'include',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCurriculumProjectScalarFieldEnum = {
  id: 'id',
  curriculumId: 'curriculumId',
  name: 'name',
  description: 'description',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCurriculumPublicationScalarFieldEnum = {
  id: 'id',
  curriculumId: 'curriculumId',
  title: 'title',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCurriculumOutboxScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  status: 'status',
  forceRegenerate: 'forceRegenerate',
  attempts: 'attempts',
  lastError: 'lastError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobCurriculumPdfOutboxScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  status: 'status',
  templateName: 'templateName',
  forceRegenerate: 'forceRegenerate',
  attempts: 'attempts',
  lastError: 'lastError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobEvaluationScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  status: 'status',
  evaluatorModel: 'evaluatorModel',
  summary: 'summary',
  desireMatchScore: 'desireMatchScore',
  competenceScore: 'competenceScore',
  overallScore: 'overallScore',
  priority: 'priority',
  desireMatchReasoning: 'desireMatchReasoning',
  competenceMatch: 'competenceMatch',
  detailedReasoning: 'detailedReasoning',
  pros: 'pros',
  cons: 'cons',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobEvaluationOutboxScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  status: 'status',
  attempts: 'attempts',
  lastError: 'lastError',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobOfferScalarFieldEnum = {
  id: 'id',
  externalId: 'externalId',
  source: 'source',
  url: 'url',
  title: 'title',
  location: 'location',
  remoteType: 'remoteType',
  rawDescription: 'rawDescription',
  descriptionMarkdown: 'descriptionMarkdown',
  datePosted: 'datePosted',
  companyId: 'companyId',
  salaryMin: 'salaryMin',
  salaryMax: 'salaryMax',
  currency: 'currency',
  contractType: 'contractType',
  roleCategory: 'roleCategory',
  experienceLevel: 'experienceLevel',
  skills: 'skills',
  status: 'status',
  evaluationProcessStatus: 'evaluationProcessStatus',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JobStatusHistoryScalarFieldEnum = {
  id: 'id',
  jobOfferId: 'jobOfferId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  createdAt: 'createdAt'
};

exports.Prisma.SyncStateScalarFieldEnum = {
  source: 'source',
  lastSyncedAt: 'lastSyncedAt',
  totalJobsExtracted: 'totalJobsExtracted',
  lastStatus: 'lastStatus',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserProfileScalarFieldEnum = {
  id: 'id',
  resumeText: 'resumeText',
  searchCriteriaText: 'searchCriteriaText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.JobCoverLetterPdfStatus = exports.$Enums.JobCoverLetterPdfStatus = {
  PENDING: 'PENDING',
  GENERATING: 'GENERATING',
  READY: 'READY',
  FAILED: 'FAILED'
};

exports.OutboxStatus = exports.$Enums.OutboxStatus = {
  PENDING: 'PENDING',
  PUBLISHED: 'PUBLISHED',
  FAILED: 'FAILED'
};

exports.JobCurriculumPdfStatus = exports.$Enums.JobCurriculumPdfStatus = {
  PENDING: 'PENDING',
  GENERATING: 'GENERATING',
  READY: 'READY',
  FAILED: 'FAILED'
};

exports.EvaluationStatus = exports.$Enums.EvaluationStatus = {
  SUCCESS: 'SUCCESS',
  UNANALYZABLE: 'UNANALYZABLE'
};

exports.EvaluatorModel = exports.$Enums.EvaluatorModel = {
  GEMINI_3_1_FLASH_LITE: 'GEMINI_3_1_FLASH_LITE',
  GEMINI_3_5_FLASH_LITE: 'GEMINI_3_5_FLASH_LITE',
  GEMMA_4_12B: 'GEMMA_4_12B',
  GEMMA_4_31B: 'GEMMA_4_31B',
  UNKNOWN: 'UNKNOWN'
};

exports.EvaluationPriority = exports.$Enums.EvaluationPriority = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  DISQUALIFIED: 'DISQUALIFIED'
};

exports.JobSource = exports.$Enums.JobSource = {
  ARBEITNOW: 'ARBEITNOW',
  REMOTIVE: 'REMOTIVE',
  JOBICY: 'JOBICY',
  WE_WORK_REMOTELY: 'WE_WORK_REMOTELY',
  HIMALAYAS: 'HIMALAYAS',
  REMOTEOK: 'REMOTEOK',
  MANUAL: 'MANUAL'
};

exports.RemoteType = exports.$Enums.RemoteType = {
  REMOTE: 'REMOTE',
  HYBRID: 'HYBRID',
  ON_SITE: 'ON_SITE',
  UNSPECIFIED: 'UNSPECIFIED'
};

exports.ExperienceLevel = exports.$Enums.ExperienceLevel = {
  ENTRY_LEVEL: 'ENTRY_LEVEL',
  JUNIOR: 'JUNIOR',
  MID: 'MID',
  SENIOR: 'SENIOR',
  LEAD: 'LEAD',
  EXECUTIVE: 'EXECUTIVE',
  UNSPECIFIED: 'UNSPECIFIED'
};

exports.ApplicationStatus = exports.$Enums.ApplicationStatus = {
  NEW: 'NEW',
  SAVED: 'SAVED',
  APPLIED: 'APPLIED',
  SCREENING: 'SCREENING',
  INTERVIEWING: 'INTERVIEWING',
  OFFER: 'OFFER',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  ARCHIVED: 'ARCHIVED'
};

exports.JobEvaluationProcessStatus = exports.$Enums.JobEvaluationProcessStatus = {
  NOT_EVALUATED: 'NOT_EVALUATED',
  PENDING: 'PENDING',
  EVALUATING: 'EVALUATING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

exports.Prisma.ModelName = {
  Company: 'Company',
  JobCoverLetter: 'JobCoverLetter',
  JobCoverLetterOutbox: 'JobCoverLetterOutbox',
  JobCurriculum: 'JobCurriculum',
  JobCurriculumWork: 'JobCurriculumWork',
  JobCurriculumProject: 'JobCurriculumProject',
  JobCurriculumPublication: 'JobCurriculumPublication',
  JobCurriculumOutbox: 'JobCurriculumOutbox',
  JobCurriculumPdfOutbox: 'JobCurriculumPdfOutbox',
  JobEvaluation: 'JobEvaluation',
  JobEvaluationOutbox: 'JobEvaluationOutbox',
  JobOffer: 'JobOffer',
  JobStatusHistory: 'JobStatusHistory',
  SyncState: 'SyncState',
  UserProfile: 'UserProfile'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
