apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: analizzatore-di-ruoli

resources:
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - minio.yaml
  - backend.yaml
  - worker-curriculum.yaml
  - worker-evaluator.yaml
  - worker-extractor.yaml
  - frontend.yaml
  - ingress.yaml
