apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resumes-pvc
  labels:
    app.kubernetes.io/name: resumes-storage
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
