apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor-remoteok
  labels:
    app: extractor-remoteok
    app.kubernetes.io/name: extractor-remoteok
    app.kubernetes.io/component: extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor-remoteok
  template:
    metadata:
      labels:
        app: extractor-remoteok
    spec:
      containers:
        - name: extractor-remoteok
          image: analizzatore-registry.localhost:5000/extractor-remoteok:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
