/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/job-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista dei nuovi annunci di lavoro non ancora catalogati (stato NEW, esclusi i DISQUALIFIED dall AI) */
        get: operations["JobOffersController_findAllNew"];
        put?: never;
        /** Crea o aggiorna un annuncio di lavoro */
        post: operations["JobOffersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera TUTTI gli annunci attivi in gestione senza paginazione (SAVED, APPLIED, SCREENING, INTERVIEWING, OFFER) */
        get: operations["JobOffersController_findActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista degli annunci conclusi o scartati dall utente (REJECTED, ARCHIVED) */
        get: operations["JobOffersController_findClosed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/disqualified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista degli annunci scartati dall AI (priorità DISQUALIFIED) */
        get: operations["JobOffersController_findDisqualified"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/paginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias per il recupero dei nuovi annunci non catalogati */
        get: operations["JobOffersController_findAllPaginated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/analytics/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera le statistiche ed il funnel di avanzamento/scarto delle candidature */
        get: operations["JobOffersController_getFunnelAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera un singolo annuncio di lavoro tramite ID */
        get: operations["JobOffersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna lo stato di un annuncio di lavoro (es. APPLIED, INTERVIEWING, REJECTED, ARCHIVED) e registra la cronologia */
        patch: operations["JobOffersController_updateStatus"];
        trace?: never;
    };
    "/evaluations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restituisce le metriche in tempo reale sullo stato di categorizzazione degli annunci */
        get: operations["EvaluationsController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera tutte le valutazioni salvate, filtrate per priorità o punteggio minimo */
        get: operations["EvaluationsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evaluations/{jobOfferId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la valutazione salvata per una specifica offerta */
        get: operations["EvaluationsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JobStatusHistoryDto: {
            id: string;
            /** @enum {string|null} */
            fromStatus: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED" | null;
            /** @enum {string} */
            toStatus: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
            /** Format: date-time */
            createdAt: string;
        };
        CreateCompanyDto: {
            name: string;
            websiteUrl?: Record<string, never> | null;
            linkedinUrl?: Record<string, never> | null;
            industry?: Record<string, never> | null;
            fundingStage?: Record<string, never> | null;
            companySizeRange?: Record<string, never> | null;
            employeeCount?: number | null;
        };
        CreateJobOfferDto: {
            externalId?: Record<string, never> | null;
            /** @enum {string} */
            source: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
            url: string;
            title: string;
            location?: Record<string, never> | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            remoteType: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
            rawDescription: string;
            descriptionMarkdown?: Record<string, never> | null;
            datePosted?: Record<string, never> | null;
            salaryMin?: Record<string, never> | null;
            salaryMax?: Record<string, never> | null;
            /** @default EUR */
            currency: Record<string, never> | null;
            contractType?: Record<string, never> | null;
            roleCategory?: Record<string, never> | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            experienceLevel: "ENTRY_LEVEL" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "EXECUTIVE" | "UNSPECIFIED";
            skills?: string[];
            /**
             * @default NEW
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
            notes?: Record<string, never> | null;
            statusHistory?: components["schemas"]["JobStatusHistoryDto"][];
            company: components["schemas"]["CreateCompanyDto"];
        };
        CompanyDto: {
            id: string;
            name: string;
            websiteUrl?: Record<string, never> | null;
            linkedinUrl?: Record<string, never> | null;
            industry?: Record<string, never> | null;
            fundingStage?: Record<string, never> | null;
            companySizeRange?: Record<string, never> | null;
            employeeCount?: number | null;
        };
        JobEvaluationDto: {
            id: string;
            jobOfferId: string;
            /** @description Punteggio di aderenza ai desiderata dell utente (0-100) */
            desireMatchScore: number;
            /** @description Punteggio di competenza tecnica (0-100) */
            competenceScore: number;
            /** @description Punteggio globale bilanciato (0-100) */
            overallScore: number;
            /** @description Livello di priorità: HIGH, MEDIUM, LOW, DISQUALIFIED */
            priority: string;
            /** @description Stato dell analisi: SUCCESS | UNANALYZABLE */
            status: string;
            /** @description Modello AI che ha analizzato l annuncio: GEMINI_3_1_FLASH_LITE | GEMMA_4_12B | UNKNOWN */
            evaluatorModel: string;
            /** @description Spiegazione sintetico aderenza desiderata */
            desireMatchReasoning?: Record<string, never> | null;
            /** @description Valutazione delle competenze dell utente rispetto al ruolo */
            competenceMatch: string;
            /** @description Spiegazione dettagliata dell AI in Markdown */
            detailedReasoning: string;
            pros?: string[] | null;
            cons?: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobOfferDto: {
            id: string;
            externalId?: Record<string, never> | null;
            /** @enum {string} */
            source: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
            url: string;
            title: string;
            location?: Record<string, never> | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            remoteType: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
            rawDescription: string;
            descriptionMarkdown?: Record<string, never> | null;
            datePosted?: Record<string, never> | null;
            company: components["schemas"]["CompanyDto"];
            salaryMin?: Record<string, never> | null;
            salaryMax?: Record<string, never> | null;
            /** @default EUR */
            currency: Record<string, never> | null;
            contractType?: Record<string, never> | null;
            roleCategory?: Record<string, never> | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            experienceLevel: "ENTRY_LEVEL" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "EXECUTIVE" | "UNSPECIFIED";
            skills?: string[];
            /**
             * @default NEW
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
            notes?: Record<string, never> | null;
            evaluation?: components["schemas"]["JobEvaluationDto"] | null;
            /**
             * @example HOT
             * @enum {string}
             */
            freshness: "HOT" | "RECENT" | "AGING" | "OLD";
            statusHistory?: components["schemas"]["JobStatusHistoryDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        UpdateJobOfferStatusDto: {
            /**
             * @description Nuovo stato dell annuncio
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    JobOffersController_findAllNew: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
                /** @description Includi anche gli annunci non ancora valutati dall AI (default: false) */
                includePending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobOfferDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_findActive: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
                /** @description Includi anche gli annunci non ancora valutati dall AI (default: false) */
                includePending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"][];
                };
            };
        };
    };
    JobOffersController_findClosed: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
                /** @description Includi anche gli annunci non ancora valutati dall AI (default: false) */
                includePending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_findDisqualified: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
                /** @description Includi anche gli annunci non ancora valutati dall AI (default: false) */
                includePending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_findAllPaginated: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "SCREENING" | "INTERVIEWING" | "OFFER" | "ACCEPTED" | "REJECTED" | "ARCHIVED";
                /** @description Includi anche gli annunci non ancora valutati dall AI (default: false) */
                includePending?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_getFunnelAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobOffersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobOffersController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobOfferStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    EvaluationsController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EvaluationsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EvaluationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobOfferId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
