/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/job-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea o aggiorna un annuncio di lavoro nel database */
        post: operations["JobOffersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/paginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista paginata degli annunci di lavoro */
        get: operations["JobOffersController_findAllPaginated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera un singolo annuncio di lavoro tramite ID */
        get: operations["JobOffersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CompanyDto: {
            id: string;
            name: string;
            websiteUrl?: string | null;
            linkedinUrl?: string | null;
            industry?: string | null;
            fundingStage?: string | null;
            companySizeRange?: string | null;
            employeeCount?: number | null;
        };
        CreateJobOfferDto: {
            externalId?: string | null;
            source: string;
            url: string;
            title: string;
            location?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            remoteType: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
            rawDescription: string;
            /** Format: date-time */
            datePosted?: string | null;
            company: components["schemas"]["CompanyDto"];
            salaryMin?: number | null;
            salaryMax?: number | null;
            /** @default EUR */
            currency: string | null;
            contractType?: string | null;
            roleCategory?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            experienceLevel: "ENTRY_LEVEL" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "EXECUTIVE" | "UNSPECIFIED";
            skills?: string[];
            /**
             * @default NEW
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "REJECTED" | "ARCHIVED";
            notes?: string | null;
        };
        JobOfferDto: {
            id: string;
            externalId?: string | null;
            source: string;
            url: string;
            title: string;
            location?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            remoteType: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
            rawDescription: string;
            /** Format: date-time */
            datePosted?: string | null;
            company: components["schemas"]["CompanyDto"];
            salaryMin?: number | null;
            salaryMax?: number | null;
            /** @default EUR */
            currency: string | null;
            contractType?: string | null;
            roleCategory?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            experienceLevel: "ENTRY_LEVEL" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "EXECUTIVE" | "UNSPECIFIED";
            skills?: string[];
            /**
             * @default NEW
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "REJECTED" | "ARCHIVED";
            notes?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    JobOffersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobOfferDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_findAllPaginated: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
}
