/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/job-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista dei nuovi annunci di lavoro non ancora catalogati (stato NEW, esclusi i DISQUALIFIED dall AI) */
        get: operations["JobOffersController_findAllNew"];
        put?: never;
        /** Crea o aggiorna un annuncio di lavoro */
        post: operations["JobOffersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera TUTTI gli annunci attivi in gestione senza paginazione (SAVED, APPLIED, SCREENING, INTERVIEWING, OFFER) */
        get: operations["JobOffersController_findActive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/closed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista degli annunci conclusi o scartati dall utente (REJECTED, ARCHIVED) */
        get: operations["JobOffersController_findClosed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/disqualified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la lista degli annunci scartati dall AI (priorità DISQUALIFIED) */
        get: operations["JobOffersController_findDisqualified"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/paginated": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias per il recupero dei nuovi annunci non catalogati */
        get: operations["JobOffersController_findAllPaginated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/analytics/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera le statistiche ed il funnel di avanzamento/scarto delle candidature */
        get: operations["JobOffersController_getFunnelAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera un singolo annuncio di lavoro tramite ID */
        get: operations["JobOffersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/{id}/curriculum/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scarica o visualizza il file PDF del curriculum personalizzato generato per l annuncio */
        get: operations["JobOffersController_getCurriculumPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-offers/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna lo stato di un annuncio di lavoro (es. APPLIED, INTERVIEWING, REJECTED, ARCHIVED) e registra la cronologia */
        patch: operations["JobOffersController_updateStatus"];
        trace?: never;
    };
    "/api/job-offers/{id}/curriculum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna i dati di personalizzazione del curriculum e rigenera il PDF */
        patch: operations["JobOffersController_updateCurriculumTailoring"];
        trace?: never;
    };
    "/api/job-offers/{id}/cover-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera i dati e lo stato della cover letter per un annuncio */
        get: operations["JobOffersController_getCoverLetter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Aggiorna i dati della cover letter e attiva la rigenerazione del PDF */
        patch: operations["JobOffersController_updateCoverLetter"];
        trace?: never;
    };
    "/api/job-offers/{id}/cover-letter/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera e trasmette lo stream del file PDF della cover letter compilata */
        get: operations["JobOffersController_getCoverLetterPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Restituisce le metriche in tempo reale sullo stato di categorizzazione degli annunci */
        get: operations["EvaluationsController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera tutte le valutazioni salvate, filtrate per priorità o punteggio minimo */
        get: operations["EvaluationsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{jobOfferId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera la valutazione salvata per una specifica offerta */
        get: operations["EvaluationsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera l'elenco di tutte le aziende registrate con i conteggi sintetici delle loro offerte */
        get: operations["CompaniesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{companyId}/job-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recupera tutte le offerte di una specifica azienda suddivise per stato (conteggi per pendenti/squalificate, dettaglio completo per le attive) */
        get: operations["CompaniesController_getCompanyJobOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkTailoringDto: {
            /** @description Nome azienda (es. MioCFO, Commigo, University of Salerno) */
            name: string;
            /** @description Posizione o titolo ricoperto */
            position?: string;
            /** @description Bullet points riformulati per l annuncio */
            summary: string;
            /** @description Se false, esclude l esperienza dal CV */
            include?: boolean;
        };
        ProjectTailoringDto: {
            /** @description Nome del progetto */
            name: string;
            /** @description Descrizione e bullet points del progetto */
            description: string;
        };
        JobCurriculumDto: {
            id: string;
            jobOfferId: string;
            /** @description Chiave di identificazione dell oggetto in S3/MinIO */
            storageKey?: string | null;
            /**
             * @description Stato di compilazione del PDF
             * @enum {string}
             */
            pdfStatus: "PENDING" | "GENERATING" | "READY" | "FAILED";
            explanation: string;
            /** @description Titolo professionale personalizzato per l annuncio */
            customLabel?: string | null;
            /** @description Esperienze lavorative modellate per l annuncio */
            work: components["schemas"]["WorkTailoringDto"][];
            /** @description Progetti tecnici modellati per l annuncio */
            projects: components["schemas"]["ProjectTailoringDto"][];
            /** @description Titoli delle pubblicazioni scientifiche selezionate */
            selectedPublicationTitles: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateCurriculumTailoringDto: {
            /** @description Titolo professionale personalizzato per l annuncio */
            customLabel?: string;
            /** @description Elenco delle esperienze lavorative da includere/modificare */
            work?: components["schemas"]["WorkTailoringDto"][];
            /** @description Elenco dei progetti tecnici da includere */
            projects?: components["schemas"]["ProjectTailoringDto"][];
            /** @description Titoli delle pubblicazioni da selezionare */
            selectedPublicationTitles?: string[];
            /** @description Spiegazione testuale delle motivazioni delle modifiche */
            explanation?: string;
        };
        JobCoverLetterDto: {
            /** @description ID univoco della cover letter */
            id: string;
            /** @description ID dell offerta di lavoro associata */
            jobOfferId: string;
            /** @description Titolo professionale personalizzato per l intestazione */
            customLabel?: string | null;
            /** @description Nome della persona destinataria */
            recipientName?: string | null;
            /** @description Titolo del team o del hiring manager */
            recipientTitle?: string | null;
            /** @description Nome dell azienda destinataria */
            recipientCompany: string;
            /** @description Location e modalita di lavoro dell azienda */
            recipientAddress?: string | null;
            /** @description Ruolo della posizione lavorativa */
            recipientRole: string;
            /** @description Data della lettera formattata in inglese */
            date: string;
            /** @description Saluto iniziale */
            salutation: string;
            /** @description Primo paragrafo: Esempio concreto MioCFO e metriche di impatto */
            experienceParagraph1: string;
            /** @description Secondo paragrafo: Metodologia AI-native in Antigravity IDE */
            experienceParagraph2: string;
            /** @description Terzo paragrafo: Motivazione specifica per l azienda */
            companyMotivation: string;
            /** @description Frase di chiusura e invito al colloquio */
            callToAction: string;
            /** @description Firma di chiusura */
            signoff: string;
            /** @description Spiegazione strategica generata dall AI */
            explanation?: string | null;
            /** @description Chiave di archiviazione del PDF su MinIO S3 */
            storageKey?: string | null;
            /**
             * @description Stato di compilazione del PDF
             * @enum {string}
             */
            pdfStatus: "PENDING" | "GENERATING" | "READY" | "FAILED";
            /**
             * Format: date-time
             * @description Data di creazione
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data di ultimo aggiornamento
             */
            updatedAt: string;
        };
        UpdateCoverLetterDto: {
            /** @description Titolo professionale personalizzato per l intestazione */
            customLabel?: string;
            /** @description Nome della persona destinataria */
            recipientName?: string;
            /** @description Titolo del team o del hiring manager */
            recipientTitle?: string;
            /** @description Nome dell azienda destinataria */
            recipientCompany?: string;
            /** @description Location e modalita di lavoro dell azienda */
            recipientAddress?: string;
            /** @description Ruolo della posizione lavorativa */
            recipientRole?: string;
            /** @description Data della lettera formattata in inglese */
            date?: string;
            /** @description Saluto iniziale */
            salutation?: string;
            /** @description Primo paragrafo: Esempio concreto MioCFO e metriche di impatto */
            experienceParagraph1?: string;
            /** @description Secondo paragrafo: Metodologia AI-native in Antigravity IDE */
            experienceParagraph2?: string;
            /** @description Terzo paragrafo: Motivazione specifica per l azienda */
            companyMotivation?: string;
            /** @description Frase di chiusura e invito al colloquio */
            callToAction?: string;
            /** @description Firma di chiusura */
            signoff?: string;
        };
        FunnelConversionRatesDto: {
            /** @description Percentuale di conversione da candidatura a colloquio */
            applicationToInterview: number;
            /** @description Percentuale di conversione da colloquio ad offerta */
            interviewToOffer: number;
            /** @description Percentuale di successo complessiva (offerte su candidature) */
            overallSuccessRate: number;
        };
        SankeyNodeDto: {
            /** @description ID univoco del nodo (es. src_ARBEITNOW, prio_HIGH, st_SAVED) */
            id: string;
            /** @description Etichetta leggibile del nodo */
            name: string;
            /**
             * @description Categoria o colonna del nodo
             * @enum {string}
             */
            category: "source" | "priority" | "selection" | "application" | "outcome";
            /** @description Volume totale degli annunci transitati o presenti nel nodo */
            count: number;
        };
        SankeyLinkDto: {
            /** @description ID del nodo sorgente */
            source: string;
            /** @description ID del nodo destinazione */
            target: string;
            /** @description Volume del flusso di annunci */
            value: number;
        };
        SankeyDataDto: {
            nodes: components["schemas"]["SankeyNodeDto"][];
            links: components["schemas"]["SankeyLinkDto"][];
        };
        JobOffersFunnelAnalyticsDto: {
            /** @description Conteggio delle offerte per stato attuale */
            statusCounts: {
                [key: string]: number;
            };
            /** @description Numero di transizioni per fase */
            stageTransitions: {
                [key: string]: number;
            };
            /** @description Rifiuti suddivisi per fase di interruzione */
            rejectionDropOffs: {
                [key: string]: number;
            };
            conversionRates: components["schemas"]["FunnelConversionRatesDto"];
            /** @description Dati per il diagramma di flusso continuo Sankey */
            sankey: components["schemas"]["SankeyDataDto"];
        };
        JobStatusHistoryDto: {
            id: string;
            /** @enum {string|null} */
            fromStatus: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED" | null;
            /** @enum {string} */
            toStatus: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            /** Format: date-time */
            createdAt: string;
        };
        CreateCompanyDto: {
            name: string;
            websiteUrl?: string | null;
            linkedinUrl?: string | null;
            industry?: string | null;
            fundingStage?: string | null;
            companySizeRange?: string | null;
            employeeCount?: number | null;
            eligibleOffersCount?: number | null;
            activeOffersCount?: number | null;
            savedOrAppliedCount?: number | null;
            newOffersCount?: number | null;
        };
        CreateJobOfferDto: {
            externalId?: string | null;
            /** @enum {string} */
            source: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
            url: string;
            title: string;
            location?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            remoteType: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
            rawDescription: string;
            descriptionMarkdown?: string | null;
            /** Format: date-time */
            datePosted?: string | null;
            salaryMin?: number | null;
            salaryMax?: number | null;
            /** @default EUR */
            currency: string | null;
            contractType?: string | null;
            roleCategory?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            experienceLevel: "ENTRY_LEVEL" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "EXECUTIVE" | "UNSPECIFIED";
            skills?: string[];
            /**
             * @default NEW
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            /**
             * @default PENDING
             * @enum {string}
             */
            evaluationProcessStatus: "NOT_EVALUATED" | "PENDING" | "EVALUATING" | "COMPLETED" | "FAILED";
            notes?: string | null;
            curriculum?: components["schemas"]["JobCurriculumDto"] | null;
            coverLetter?: components["schemas"]["JobCoverLetterDto"] | null;
            statusHistory?: components["schemas"]["JobStatusHistoryDto"][];
            company: components["schemas"]["CreateCompanyDto"];
        };
        CompanyDto: {
            id: string;
            name: string;
            websiteUrl?: string | null;
            linkedinUrl?: string | null;
            industry?: string | null;
            fundingStage?: string | null;
            companySizeRange?: string | null;
            employeeCount?: number | null;
            eligibleOffersCount?: number | null;
            activeOffersCount?: number | null;
            savedOrAppliedCount?: number | null;
            newOffersCount?: number | null;
        };
        JobEvaluationDto: {
            id: string;
            jobOfferId: string;
            /** @description Punteggio di aderenza ai desiderata dell utente (0-100) */
            desireMatchScore: number;
            /** @description Punteggio di competenza tecnica (0-100) */
            competenceScore: number;
            /** @description Punteggio globale bilanciato (0-100) */
            overallScore: number;
            /** @description Livello di priorità: HIGH, MEDIUM, LOW, DISQUALIFIED */
            priority: string;
            /** @description Stato dell analisi: SUCCESS | UNANALYZABLE */
            status: string;
            /** @description Modello AI che ha analizzato l annuncio: GEMINI_3_1_FLASH_LITE | GEMMA_4_12B | UNKNOWN */
            evaluatorModel: string;
            /** @description Sintesi/Riassunto dell annuncio di lavoro generato dall AI */
            summary?: string | null;
            /** @description Spiegazione sintetica aderenza desiderata */
            desireMatchReasoning?: string | null;
            /** @description Valutazione delle competenze dell utente rispetto al ruolo */
            competenceMatch: string;
            /** @description Spiegazione dettagliata dell AI in Markdown */
            detailedReasoning: string;
            pros?: string[] | null;
            cons?: string[] | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        JobOfferDto: {
            id: string;
            externalId?: string | null;
            /** @enum {string} */
            source: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
            url: string;
            title: string;
            location?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            remoteType: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
            rawDescription: string;
            descriptionMarkdown?: string | null;
            /** Format: date-time */
            datePosted?: string | null;
            company: components["schemas"]["CompanyDto"];
            salaryMin?: number | null;
            salaryMax?: number | null;
            /** @default EUR */
            currency: string | null;
            contractType?: string | null;
            roleCategory?: string | null;
            /**
             * @default UNSPECIFIED
             * @enum {string}
             */
            experienceLevel: "ENTRY_LEVEL" | "JUNIOR" | "MID" | "SENIOR" | "LEAD" | "EXECUTIVE" | "UNSPECIFIED";
            skills?: string[];
            /**
             * @default NEW
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            /**
             * @default PENDING
             * @enum {string}
             */
            evaluationProcessStatus: "NOT_EVALUATED" | "PENDING" | "EVALUATING" | "COMPLETED" | "FAILED";
            notes?: string | null;
            evaluation?: components["schemas"]["JobEvaluationDto"] | null;
            curriculum?: components["schemas"]["JobCurriculumDto"] | null;
            coverLetter?: components["schemas"]["JobCoverLetterDto"] | null;
            /**
             * @example HOT
             * @enum {string}
             */
            freshness: "HOT" | "RECENT" | "AGING" | "OLD";
            statusHistory?: components["schemas"]["JobStatusHistoryDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaginatedMetaDto: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        UpdateJobOfferStatusDto: {
            /**
             * @description Nuovo stato dell annuncio
             * @enum {string}
             */
            status: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
        };
        ActiveProcessingJobDto: {
            /** @description ID univoco dell annuncio */
            id: string;
            /** @description Titolo della posizione lavorativa */
            title: string;
            /** @description Nome dell azienda */
            companyName: string;
            /** @description Luogo di lavoro */
            location: string | null;
            /** @description Modalità di lavoro: REMOTE | HYBRID | ON_SITE | UNSPECIFIED */
            remoteType: string;
            /** @description Fonte dell annuncio */
            source: string;
            /** @description Stato di avanzamento: PENDING | EVALUATING */
            evaluationProcessStatus: string;
            /** @description Anteprima sintetica della descrizione */
            descriptionSnippet: string | null;
            /** @description Range salariale formattato */
            salaryRange: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        RecentEvaluatedJobDto: {
            /** @description ID della valutazione */
            id: string;
            /** @description ID dell annuncio correlato */
            jobOfferId: string;
            /** @description Titolo della posizione */
            title: string;
            /** @description Nome azienda */
            companyName: string;
            /** @description Punteggio globale assegnato da Gemini */
            overallScore: number;
            /** @description Priorità assegnata */
            priority: string;
            /** @description Modello AI utilizzato */
            evaluatorModel: string;
            /** @description Sintesi della valutazione */
            summary: string | null;
            /** Format: date-time */
            evaluatedAt: string;
        };
        CategorizationStatusDto: {
            /** @description Numero totale di annunci nel database */
            totalJobs: number;
            /** @description Numero di annunci già valutati con successo */
            evaluatedJobs: number;
            /** @description Numero di annunci in coda o in lavorazione */
            pendingJobs: number;
            /** @description Numero di annunci attualmente sotto elaborazione attiva con Gemini */
            evaluatingCount: number;
            /** @description Indica se il processo di categorizzazione è attualmente attivo */
            isCategorizing: boolean;
            /** @description Indica se il profilo utente è completo di CV e criteri */
            isProfileComplete: boolean;
            /** @description Messaggio sintetico sullo stato */
            message: string;
            /** @description Lista dei job attualmente in elaborazione o in coda */
            activeJobs: components["schemas"]["ActiveProcessingJobDto"][];
            /** @description Ultime valutazioni completate */
            recentEvaluatedJobs: components["schemas"]["RecentEvaluatedJobDto"][];
        };
        CompanySummaryDto: {
            id: string;
            name: string;
            websiteUrl?: string | null;
            linkedinUrl?: string | null;
            industry?: string | null;
            fundingStage?: string | null;
            companySizeRange?: string | null;
            employeeCount?: number | null;
            eligibleOffersCount?: number | null;
            activeOffersCount?: number | null;
            savedOrAppliedCount?: number | null;
            newOffersCount?: number | null;
            /** @description Numero totale di offerte collegate a questa azienda */
            totalOffersCount: number;
            /** @description Numero di offerte ancora da elaborare dall AI */
            pendingEvaluationCount: number;
            /** @description Numero di offerte squalificate dall AI */
            disqualifiedCount: number;
        };
        CompanyJobOffersCountsDto: {
            /** @description Numero totale di offerte collegate all azienda */
            totalOffers: number;
            /** @description Numero di offerte in attesa di valutazione AI */
            pendingEvaluationCount: number;
            /** @description Numero di offerte squalificate dall AI */
            disqualifiedCount: number;
            /** @description Numero di offerte idonee */
            eligibleOffersCount: number;
            /** @description Numero di offerte attualmente attive */
            activeOffersCount: number;
            /** @description Numero di offerte salvate o applicate */
            savedOrAppliedCount: number;
            /** @description Numero di offerte in stato NEW */
            newOffersCount: number;
        };
        CompanyJobOffersBreakdownDto: {
            company: components["schemas"]["CompanyDto"];
            counts: components["schemas"]["CompanyJobOffersCountsDto"];
            /** @description Informazioni complete delle sole offerte idonee (escluse quelle squalificate ed in attesa di valutazione) */
            offers: components["schemas"]["JobOfferDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    JobOffersController_findAllNew: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobOfferDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_findActive: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"][];
                };
            };
        };
    };
    JobOffersController_findClosed: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_findDisqualified: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_findAllPaginated: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Filtra per freschezza dell annuncio (HOT, RECENT, AGING, OLD) */
                freshness?: "HOT" | "RECENT" | "AGING" | "OLD";
                /** @description Filtra per priorità AI: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string;
                /** @description Filtra per punteggio minimo aderenza ai desiderata (0-100) */
                minDesireScore?: number;
                /** @description Filtra per punteggio minimo competenza tecnica (0-100) */
                minCompetenceScore?: number;
                /** @description Filtra per punteggio globale minimo (0-100) */
                minScore?: number;
                /** @description Filtra per modalità di lavoro (REMOTE, HYBRID, ON_SITE) */
                remoteType?: "REMOTE" | "HYBRID" | "ON_SITE" | "UNSPECIFIED";
                /** @description Cerca per testo nel titolo o nel nome azienda */
                search?: string;
                /** @description Filtra per fonte dell annuncio (ARBEITNOW, REMOTIVE) */
                source?: "ARBEITNOW" | "REMOTIVE" | "JOBICY" | "WE_WORK_REMOTELY" | "HIMALAYAS" | "REMOTEOK" | "MANUAL";
                /** @description Filtra per modello AI utilizzato per l analisi (es. GEMINI_3_1_FLASH_LITE, GEMMA_4_12B) */
                evaluatorModel?: string;
                /** @description Filtra per stato dell annuncio (es. NEW, SAVED, APPLIED, INTERVIEWING, REJECTED, ARCHIVED) */
                status?: "NEW" | "SAVED" | "APPLIED" | "INTERVIEWING" | "OFFER" | "REJECTED" | "ARCHIVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["JobOfferDto"][];
                        meta?: components["schemas"]["PaginatedMetaDto"];
                    };
                };
            };
        };
    };
    JobOffersController_getFunnelAnalytics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOffersFunnelAnalyticsDto"];
                };
            };
        };
    };
    JobOffersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_getCurriculumPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File PDF del curriculum personalizzato */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    JobOffersController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateJobOfferStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_updateCurriculumTailoring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCurriculumTailoringDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_getCoverLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCoverLetterDto"];
                };
            };
        };
    };
    JobOffersController_updateCoverLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCoverLetterDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOfferDto"];
                };
            };
        };
    };
    JobOffersController_getCoverLetterPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File binario PDF trasmesso come stream inline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EvaluationsController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategorizationStatusDto"];
                };
            };
        };
    };
    EvaluationsController_findAll: {
        parameters: {
            query?: {
                /** @description Filtra per priorità: HIGH, MEDIUM, LOW, DISQUALIFIED */
                priority?: string | null;
                /** @description Filtra per punteggio minimo aderenza desiderata (0-100) */
                minDesireScore?: number | null;
                /** @description Filtra per punteggio minimo (0-100) */
                minScore?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEvaluationDto"][];
                };
            };
        };
    };
    EvaluationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobOfferId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEvaluationDto"];
                };
            };
        };
    };
    CompaniesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySummaryDto"][];
                };
            };
        };
    };
    CompaniesController_getCompanyJobOffers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID dell'azienda */
                companyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyJobOffersBreakdownDto"];
                };
            };
        };
    };
}
